//! BoringSSL's SPAKE2 over edwards25519, as used by ADB pairing.
//!
//! This is **not** RFC 9382 SPAKE2. It is BoringSSL's own construction
//! (`crypto/curve25519/spake25519.cc`), so no existing Rust crate implements
//! it. Ported from that source, which is the normative description of what
//! `adbd` expects:
//!
//! - M and N are fixed edwards25519 points, generated by hashing
//!   "edwards25519 point generation seed (M)" / "(N)"; their encodings are
//!   copied from the BoringSSL comments and checked in a test.
//! - The private scalar is a reduced 64-byte random, multiplied by the
//!   cofactor 8 so that the peer's torsion component cancels.
//! - The password scalar is `SHA512(password)` reduced, then nudged by adding
//!   1, 2 or 4 times the group order so that its low three bits are clear.
//!   BoringSSL does this to work around an old copy-paste bug, and the wire
//!   format depends on it, so we reproduce it exactly.
//! - The key is SHA-512 over a transcript of length-prefixed fields.
//!
//! Naming follows the original: "alice" is the client, "bob" the server.

use curve25519_dalek::edwards::{CompressedEdwardsY, EdwardsPoint};
use curve25519_dalek::scalar::Scalar;
use sha2::{Digest, Sha512};
use subtle::{Choice, ConditionallySelectable};

use crate::error::{Error, Result};

/// M, from the BoringSSL comment block.
const M_ENCODED: [u8; 32] = [
    0x5a, 0xda, 0x7e, 0x4b, 0xf6, 0xdd, 0xd9, 0xad, 0xb6, 0x62, 0x6d, 0x32, 0x13, 0x1c, 0x6b, 0x5c,
    0x51, 0xa1, 0xe3, 0x47, 0xa3, 0x47, 0x8f, 0x53, 0xcf, 0xcf, 0x44, 0x1b, 0x88, 0xee, 0xd1, 0x2e,
];

/// N, from the BoringSSL comment block.
const N_ENCODED: [u8; 32] = [
    0x10, 0xe3, 0xdf, 0x0a, 0xe3, 0x7d, 0x8e, 0x7a, 0x99, 0xb5, 0xfe, 0x74, 0xb4, 0x46, 0x72, 0x10,
    0x3d, 0xbd, 0xdc, 0xbd, 0x06, 0xaf, 0x68, 0x0d, 0x71, 0x32, 0x9a, 0x11, 0x69, 0x3b, 0xc7, 0x78,
];

/// l = 2^252 + 27742317777372353535851937790883648493, the order of the
/// prime-order subgroup, little-endian. Checked against dalek in a test.
const GROUP_ORDER: [u8; 32] = [
    0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10,
];

pub const MSG_LEN: usize = 32;
pub const KEY_LEN: usize = 64;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    /// The side that masks with M. ADB's pairing client.
    Alice,
    /// The side that masks with N. ADB's pairing server (the phone).
    Bob,
}

pub struct Spake2 {
    role: Role,
    my_name: Vec<u8>,
    their_name: Vec<u8>,
    private: Scalar,
    password_hash: [u8; 64],
    password_scalar: [u8; 32],
    my_msg: [u8; MSG_LEN],
}

impl Spake2 {
    /// Starts the exchange and produces our message. `password` is the pairing
    /// code with the TLS exported keying material appended. The names are
    /// compared by both sides and include their NUL byte in ADB's usage.
    pub fn start(role: Role, my_name: &[u8], their_name: &[u8], password: &[u8]) -> Self {
        Self::start_with_private(role, my_name, their_name, password, random_scalar())
    }

    fn start_with_private(
        role: Role,
        my_name: &[u8],
        their_name: &[u8],
        password: &[u8],
        private: Scalar,
    ) -> Self {
        let password_hash: [u8; 64] = Sha512::digest(password).into();
        let password_scalar = password_scalar(&password_hash);

        // P = (8·private)·B. The base point has prime order, so reducing the
        // multiplied scalar changes nothing.
        let point = EdwardsPoint::mul_base(&(private * Scalar::from(8u8)));
        let mask = mul_raw(&base_point(mask_for(role)), &password_scalar);
        let my_msg = (point + mask).compress().to_bytes();

        Self {
            role,
            my_name: my_name.to_vec(),
            their_name: their_name.to_vec(),
            private,
            password_hash,
            password_scalar,
            my_msg,
        }
    }

    pub fn message(&self) -> &[u8; MSG_LEN] {
        &self.my_msg
    }

    /// Consumes the peer's message and derives the 64-byte shared key.
    pub fn finish(self, their_msg: &[u8]) -> Result<[u8; KEY_LEN]> {
        let their_msg: [u8; MSG_LEN] = their_msg
            .try_into()
            .map_err(|_| Error::Protocol(format!("SPAKE2 message must be {MSG_LEN} bytes")))?;
        let their_point = CompressedEdwardsY(their_msg)
            .decompress()
            .ok_or_else(|| Error::Protocol("peer's SPAKE2 point is not on the curve".into()))?;

        let peer_mask_base = base_point(match self.role {
            Role::Alice => Role::Bob,
            Role::Bob => Role::Alice,
        });
        let unmasked = their_point - mul_raw(&peer_mask_base, &self.password_scalar);
        // 8·private·Q, with the cofactor multiplication done on the point so
        // the peer's torsion component cancels exactly as in BoringSSL.
        let shared = (self.private * unmasked.mul_by_cofactor()).compress().to_bytes();

        let mut hash = Sha512::new();
        let (first, second, first_msg, second_msg) = match self.role {
            Role::Alice => (&self.my_name, &self.their_name, &self.my_msg, &their_msg),
            Role::Bob => (&self.their_name, &self.my_name, &their_msg, &self.my_msg),
        };
        for field in [first.as_slice(), second.as_slice(), first_msg, second_msg, &shared, &self.password_hash] {
            hash.update((field.len() as u64).to_le_bytes());
            hash.update(field);
        }
        Ok(hash.finalize().into())
    }
}

fn mask_for(role: Role) -> Role {
    role
}

fn base_point(role: Role) -> EdwardsPoint {
    let encoded = match role {
        Role::Alice => M_ENCODED,
        Role::Bob => N_ENCODED,
    };
    CompressedEdwardsY(encoded).decompress().expect("M and N are valid points")
}

fn random_scalar() -> Scalar {
    let mut wide = [0u8; 64];
    rand::RngCore::fill_bytes(&mut rand::rngs::OsRng, &mut wide);
    Scalar::from_bytes_mod_order_wide(&wide)
}

/// `SHA512(password)` reduced, then adjusted so its low three bits are zero by
/// adding l, 2l and 4l as needed (BoringSSL's "password scalar hack").
fn password_scalar(password_hash: &[u8; 64]) -> [u8; 32] {
    let mut scalar = Scalar::from_bytes_mod_order_wide(password_hash).to_bytes();
    let mut multiple = GROUP_ORDER;
    for bit in 0..3 {
        if scalar[0] & (1 << bit) != 0 {
            add_assign(&mut scalar, &multiple);
        }
        double_assign(&mut multiple);
    }
    debug_assert_eq!(scalar[0] & 7, 0);
    scalar
}

/// 256-bit little-endian addition, wrapping (values stay below 2^256 here).
fn add_assign(value: &mut [u8; 32], addend: &[u8; 32]) {
    let mut carry = 0u16;
    for i in 0..32 {
        let sum = u16::from(value[i]) + u16::from(addend[i]) + carry;
        value[i] = sum as u8;
        carry = sum >> 8;
    }
}

fn double_assign(value: &mut [u8; 32]) {
    let copy = *value;
    add_assign(value, &copy);
}

/// Scalar multiplication by a raw 256-bit value, without reducing it mod the
/// group order. The password scalar is deliberately larger than the order, and
/// reducing it would change the result for points with a torsion component.
fn mul_raw(point: &EdwardsPoint, scalar: &[u8; 32]) -> EdwardsPoint {
    let mut result = EdwardsPoint::default();
    for byte in scalar.iter().rev() {
        for bit in (0..8).rev() {
            result = result + result;
            let sum = result + point;
            result = EdwardsPoint::conditional_select(&result, &sum, Choice::from((byte >> bit) & 1));
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    const CLIENT: &[u8] = b"adb pair client\0";
    const SERVER: &[u8] = b"adb pair server\0";

    #[test]
    fn m_and_n_match_the_documented_coordinates() {
        // From the BoringSSL comment block.
        let m = base_point(Role::Alice);
        let n = base_point(Role::Bob);
        assert_eq!(m.compress().to_bytes(), M_ENCODED);
        assert_eq!(n.compress().to_bytes(), N_ENCODED);
        assert_ne!(m, n);
    }

    #[test]
    fn password_scalar_has_its_low_three_bits_cleared() {
        for password in [b"000000".as_slice(), b"123456", b"", b"a longer secret"] {
            let hash: [u8; 64] = Sha512::digest(password).into();
            let scalar = password_scalar(&hash);
            assert_eq!(scalar[0] & 7, 0, "password {password:?}");
            // Still congruent to the reduced hash modulo the group order.
            assert_eq!(
                Scalar::from_bytes_mod_order(scalar),
                Scalar::from_bytes_mod_order_wide(&hash)
            );
        }
    }

    #[test]
    fn mul_raw_agrees_with_scalar_mul_for_small_values() {
        let point = base_point(Role::Alice);
        for k in [0u8, 1, 2, 3, 8, 200] {
            let mut raw = [0u8; 32];
            raw[0] = k;
            assert_eq!(mul_raw(&point, &raw), Scalar::from(k) * point, "k = {k}");
        }
    }

    #[test]
    fn both_sides_agree_on_the_key() {
        let password = b"739345 plus exported key material";
        let alice = Spake2::start(Role::Alice, CLIENT, SERVER, password);
        let bob = Spake2::start(Role::Bob, SERVER, CLIENT, password);

        let alice_msg = *alice.message();
        let bob_msg = *bob.message();
        let alice_key = alice.finish(&bob_msg).unwrap();
        let bob_key = bob.finish(&alice_msg).unwrap();

        assert_eq!(alice_key, bob_key);
        assert_ne!(alice_key, [0u8; KEY_LEN]);
    }

    #[test]
    fn different_passwords_give_different_keys() {
        let alice = Spake2::start(Role::Alice, CLIENT, SERVER, b"111111");
        let bob = Spake2::start(Role::Bob, SERVER, CLIENT, b"222222");
        let alice_msg = *alice.message();
        let bob_msg = *bob.message();
        assert_ne!(alice.finish(&bob_msg).unwrap(), bob.finish(&alice_msg).unwrap());
    }

    #[test]
    fn transcript_order_matters() {
        // Swapping the names must change the key: alice and bob hash the
        // transcript in opposite orders, so mismatched roles cannot agree.
        let password = b"424242";
        let alice = Spake2::start(Role::Alice, CLIENT, SERVER, password);
        let wrong = Spake2::start(Role::Bob, CLIENT, SERVER, password);
        let alice_msg = *alice.message();
        let wrong_msg = *wrong.message();
        assert_ne!(alice.finish(&wrong_msg).unwrap(), wrong.finish(&alice_msg).unwrap());
    }

    #[test]
    fn group_order_constant_matches_dalek() {
        assert_eq!(Scalar::from_bytes_mod_order(GROUP_ORDER), Scalar::ZERO);
        // One less than the order must not reduce to zero.
        let mut below = GROUP_ORDER;
        below[0] -= 1;
        assert_ne!(Scalar::from_bytes_mod_order(below), Scalar::ZERO);
    }

    #[test]
    fn rejects_a_bad_peer_message() {
        // Find an encoding that is not a curve point; roughly half are not.
        let bad = (0u8..=255)
            .map(|i| {
                let mut bytes = [0u8; 32];
                bytes[0] = i;
                bytes[31] = 0x40;
                bytes
            })
            .find(|bytes| CompressedEdwardsY(*bytes).decompress().is_none())
            .expect("some encoding is not on the curve");

        let alice = Spake2::start(Role::Alice, CLIENT, SERVER, b"000000");
        let err = alice.finish(&bad).unwrap_err();
        assert!(matches!(err, Error::Protocol(_)), "{err}");
    }

    #[test]
    fn rejects_a_short_peer_message() {
        let alice = Spake2::start(Role::Alice, CLIENT, SERVER, b"000000");
        assert!(alice.finish(&[0u8; 31]).is_err());
    }

    #[test]
    fn a_fixed_private_scalar_gives_a_reproducible_message() {
        // Guards the message construction (P + mask) against accidental change.
        let private = Scalar::from_bytes_mod_order([7u8; 32]);
        let one = Spake2::start_with_private(Role::Alice, CLIENT, SERVER, b"123456", private);
        let two = Spake2::start_with_private(Role::Alice, CLIENT, SERVER, b"123456", private);
        assert_eq!(one.message(), two.message());
        assert_ne!(one.message(), &[0u8; MSG_LEN]);
    }
}
